name: BridgeFight
version: 1.0.1
main: id.hyperionx.bridgefight.Main
api-version: 1.21
authors: [Reyhan]
description: A BridgeFight plugin for Zelvera Minecraft server.
website: https://github.com/Hannzzzz/zelvera-bridgewars

commands:
  bridgefight:
    description: Main BridgeFight command
    aliases: [bf]
    usage: /<command> [join|leave|stats|shop]
  bfadmin:
    description: Admin commands for BridgeFight
    aliases: [bfa]
    usage: /<command> [start|stop|reload]
    permission: bridgefight.admin

permissions:
  bridgefight.admin:
    description: Allows access to admin commands
    default: op
  bridgefight.play:
    description: Allows playing BridgeFight
    default: true